# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotfiles < Formula
  desc "Developer tooling"
  homepage "https://github.com/geoffjay/dotfiles"
  version "0.1.2-beta"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffjay/dotfiles/releases/download/v0.1.2-beta/dotfiles_Darwin_x86_64.tar.gz"
      sha256 "89aaf08e28edc443620c489037aff5b0dc3ce719b0047e027f6a3a6d04201cc1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/geoffjay/dotfiles/releases/download/v0.1.2-beta/dotfiles_linux_x86_64.tar.gz"
      sha256 "a264590e750fc525a2e3b34919d58dc53d2464376c4e7b3f4643078b9d5be7dc"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/geoffjay/dotfiles/releases/download/v0.1.2-beta/dotfiles_linux_armv6.tar.gz"
      sha256 "9ff48a4123c4104d4c3d5309f13237ce5c9af37e404c1d7f73656fca4cb9dcc1"
    end
  end

  depends_on "go"

  def install
    bin.install "dotfiles"
  end

  test do
    system "#{bin}/dotfiles version"
  end
end
