# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Horde < Formula
  desc "Distributed multi-agent system built on the Google V2 ADK"
  homepage "https://github.com/geoffjay/horde"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffjay/horde/releases/download/v0.3.0/horde_0.3.0_macOS_amd64.tar.gz"
      sha256 "e324295b99cac45ff7ea4d08b8210bbc2c60b301961b7e37f6348a33fa92bc1a"

      define_method(:install) do
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffjay/horde/releases/download/v0.3.0/horde_0.3.0_macOS_arm64.tar.gz"
      sha256 "c394a82f778b4aace3cf8c8885ee9cd1dd79bf3affeefd7caf4870bdc37843f3"

      define_method(:install) do
        bin.install "horde"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffjay/horde/releases/download/v0.3.0/horde_0.3.0_linux_amd64.tar.gz"
      sha256 "e0db3c7e47138dd623bd1fda91b4c771c38f5576ddadd7ff3aa6c76eda405a5c"
      define_method(:install) do
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffjay/horde/releases/download/v0.3.0/horde_0.3.0_linux_arm64.tar.gz"
      sha256 "b5f50ab40ddd949a2c240415f55801194e0fe831a2b8a705c22a3cebe4794742"
      define_method(:install) do
        bin.install "horde"
      end
    end
  end

  test do
    assert_match "horde", shell_output("#{bin}/horde --version")
  end
end
