# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Horde < Formula
  desc "Distributed multi-agent system built on the Google V2 ADK"
  homepage "https://github.com/geoffjay/horde"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffjay/horde/releases/download/v0.1.0/horde_0.1.0_macOS_amd64.tar.gz"
      sha256 "5929ca5c6810a071483d5cba1d1deaaf15fe66865de776cf76fe8c5868108ea9"

      define_method(:install) do
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffjay/horde/releases/download/v0.1.0/horde_0.1.0_macOS_arm64.tar.gz"
      sha256 "aa95f9769e71f0ad9d679e27ac7a05263f57dcd49ef82b99b19146be519dc14c"

      define_method(:install) do
        bin.install "horde"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffjay/horde/releases/download/v0.1.0/horde_0.1.0_linux_amd64.tar.gz"
      sha256 "b74675db676bc721988d1dcbd3a030275eb916c5a678ff9d78224ccf147fba70"
      define_method(:install) do
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffjay/horde/releases/download/v0.1.0/horde_0.1.0_linux_arm64.tar.gz"
      sha256 "684b717a40dee651a8c0c24653ff7a132e00913f24e1aaac14a39bb6e6b9faf0"
      define_method(:install) do
        bin.install "horde"
      end
    end
  end

  test do
    assert_match "horde", shell_output("#{bin}/horde --version")
  end
end
