# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Horde < Formula
  desc "Distributed multi-agent system built on the Google V2 ADK"
  homepage "https://github.com/geoffjay/horde"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffjay/horde/releases/download/v0.2.0/horde_0.2.0_macOS_amd64.tar.gz"
      sha256 "711108c38837827c94ffecd6546446d349b1a08530ff418195513caaa5632c99"

      define_method(:install) do
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffjay/horde/releases/download/v0.2.0/horde_0.2.0_macOS_arm64.tar.gz"
      sha256 "5e0c2c37d03dc554e8b30c181a29d69758b7b8dc30c142e312b4ad34f6d2d102"

      define_method(:install) do
        bin.install "horde"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffjay/horde/releases/download/v0.2.0/horde_0.2.0_linux_amd64.tar.gz"
      sha256 "fd84ea864585ee7258c7366fc359e5caf63e9946b3599e42870186a8429616d8"
      define_method(:install) do
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffjay/horde/releases/download/v0.2.0/horde_0.2.0_linux_arm64.tar.gz"
      sha256 "010fb9b99cc6c296b96911ba764d059bc87a81db85314d92b75e9db58f5a5a30"
      define_method(:install) do
        bin.install "horde"
      end
    end
  end

  test do
    assert_match "horde", shell_output("#{bin}/horde --version")
  end
end
