# This file was generated by GoReleaser. DO NOT EDIT.
class SgTooling < Formula
  desc "Developer tooling"
  homepage "https://github.com/geoffjay/7g-tooling"
  version "0.1.6-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/geoffjay/7g-tooling/releases/download/v0.1.6-beta/7g-tooling_Darwin_x86_64.tar.gz"
    sha256 "f8120e305138b67ebdf08c199652754c05d6bbe05ed8021a5c446964ead99c58"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "7g"
  end

  test do
    system "#{bin}/7g version"
  end
end
