# This file was generated by GoReleaser. DO NOT EDIT.
class SgTooling < Formula
  desc "Developer tooling"
  homepage "https://github.com/geoffjay/7g-tooling"
  version "0.1.4-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/geoffjay/7g-tooling/releases/download/v0.1.4-beta/7g-tooling_Darwin_x86_64.tar.gz"
    sha256 "0589f0be1a1b95c87c4f22a73870be60e944cb4313ef9cdb6b1bb251bf5d1663"
  elsif OS.linux?
  end

  depends_on "go"

  def install
    bin.install "7g"
  end

  test do
    system "#{bin}/7g version"
  end
end
