# This file was generated by GoReleaser. DO NOT EDIT.
class SgTooling < Formula
  desc "Developer tooling"
  homepage "https://github.com/geoffjay/7g-tooling"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/geoffjay/7g-tooling/releases/download/v0.2.0/7g-tooling_Darwin_x86_64.tar.gz"
    sha256 "a022b81022772477798304e58d46638017ccb595c42281bdcd9f60cbd71b08f1"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "7g"
  end

  test do
    system "#{bin}/7g version"
  end
end
